const Admin = {
    Users: [
        {
            id: 1,
            first_name: "John",
            last_name: "Doe",
            full_address: "123 Main St, Anytown, USA",
            zip_code: "10116",
            country: "USA",
            city: "New York",
            state: "NY",
            phone: "+1 (123) 456-7890",
            email: "admin@example.com",
            image: "https://ui-avatars.com/api/?name=John+Doe&background=0D8ABC&color=fff",
            balance: 1561.02,
            status: true,
            is_admin: true,
        },
        {
            id: 2,
            first_name: "Demo",
            last_name: "Site",
            full_address: "123 Main St, Anytown, USA",
            zip_code: "10116",
            country: "Egypt",
            city: "New York",
            state: "NY",
            phone: "+1 (123) 456-7890",
            email: "demo@example.com",
            image: "https://ui-avatars.com/api/?name=Demo+Site&background=FF3333&color=fff",
            balance: 52.02,
            status: false,
            is_admin: false,
        },
        {
            id: 3,
            first_name: "Emma",
            last_name: "Clark",
            full_address: "56 Pine Ave, San Diego, CA, USA",
            zip_code: "92101",
            country: "USA",
            city: "San Diego",
            state: "CA",
            phone: "+1 (619) 555-9876",
            email: "emma.clark@example.com",
            image: "https://ui-avatars.com/api/?name=Emma+Clark&background=0D8ABC&color=fff",
            balance: 1280.55,
            status: true,
            is_admin: true,
        },
        {
            id: 4,
            first_name: "Liam",
            last_name: "Nguyen",
            full_address: "77 Lotus St, Toronto, ON, Canada",
            zip_code: "M5V 2T6",
            country: "Canada",
            city: "Toronto",
            state: "ON",
            phone: "+1 (416) 555-2010",
            email: "liam.nguyen@example.ca",
            image: "https://ui-avatars.com/api/?name=Liam+Nguyen&background=0D8ABC&color=fff",
            balance: 2120.1,
            status: false,
            is_admin: false,
        },
        {
            id: 5,
            first_name: "Ava",
            last_name: "Martinez",
            full_address: "89 Calle Real, Mexico City, CDMX, Mexico",
            zip_code: "01000",
            country: "Mexico",
            city: "Mexico City",
            state: "CDMX",
            phone: "+52 (55) 5555-1234",
            email: "ava.martinez@example.mx",
            image: "https://ui-avatars.com/api/?name=Ava+Martinez&background=0D8ABC&color=fff",
            balance: 890.75,
            status: true,
            is_admin: false,
        },
        {
            id: 6,
            first_name: "Noah",
            last_name: "Kim",
            full_address: "14 Han Rd, Seoul, South Korea",
            zip_code: "04524",
            country: "South Korea",
            city: "Seoul",
            state: "Seoul",
            phone: "+82 2-555-2345",
            email: "noah.kim@example.kr",
            image: "https://ui-avatars.com/api/?name=Noah+Kim&background=0D8ABC&color=fff",
            balance: 1364.9,
            status: false,
            is_admin: false,
        },
        {
            id: 7,
            first_name: "Isabella",
            last_name: "Schmidt",
            full_address: "20 Hauptstrasse, Berlin, Germany",
            zip_code: "10115",
            country: "Germany",
            city: "Berlin",
            state: "Berlin",
            phone: "+49 30 123456",
            email: "isabella.schmidt@example.de",
            image: "https://ui-avatars.com/api/?name=Isabella+Schmidt&background=0D8ABC&color=fff",
            balance: 1784.0,
            status: true,
            is_admin: true,
        },
        {
            id: 8,
            first_name: "Lucas",
            last_name: "Brown",
            full_address: "10 Victoria St, Sydney, NSW, Australia",
            zip_code: "2000",
            country: "Australia",
            city: "Sydney",
            state: "NSW",
            phone: "+61 2 9876 5432",
            email: "lucas.brown@example.au",
            image: "https://ui-avatars.com/api/?name=Lucas+Brown&background=0D8ABC&color=fff",
            balance: 1092.45,
            status: false,
            is_admin: false,
        },
        {
            id: 9,
            first_name: "Mia",
            last_name: "Dubois",
            full_address: "33 Rue Saint-Honoré, Paris, France",
            zip_code: "75001",
            country: "France",
            city: "Paris",
            state: "IDF",
            phone: "+33 1 45 67 89 00",
            email: "mia.dubois@example.fr",
            image: "https://ui-avatars.com/api/?name=Mia+Dubois&background=0D8ABC&color=fff",
            balance: 1452.25,
            status: true,
            is_admin: false,
        },
        {
            id: 10,
            first_name: "William",
            last_name: "Singh",
            full_address: "18 MG Rd, Mumbai, India",
            zip_code: "400001",
            country: "India",
            city: "Mumbai",
            state: "MH",
            phone: "+91 22 2345 6789",
            email: "william.singh@example.in",
            image: "https://ui-avatars.com/api/?name=William+Singh&background=0D8ABC&color=fff",
            balance: 920.7,
            status: false,
            is_admin: false,
        },
        {
            id: 11,
            first_name: "Olivia",
            last_name: "Rossi",
            full_address: "77 Via Roma, Rome, Italy",
            zip_code: "00100",
            country: "Italy",
            city: "Rome",
            state: "RM",
            phone: "+39 06 1234 5678",
            email: "olivia.rossi@example.it",
            image: "https://ui-avatars.com/api/?name=Olivia+Rossi&background=0D8ABC&color=fff",
            balance: 1310.35,
            status: true,
            is_admin: true,
        },
        {
            id: 12,
            first_name: "James",
            last_name: "Ali",
            full_address: "44 Nile St, Cairo, Egypt",
            zip_code: "11511",
            country: "Egypt",
            city: "Cairo",
            state: "CAI",
            phone: "+20 2 2461 1234",
            email: "james.ali@example.eg",
            image: "https://ui-avatars.com/api/?name=James+Ali&background=0D8ABC&color=fff",
            balance: 875.4,
            status: true,
            is_admin: false,
        },
        {
            id: 13,
            first_name: "Chloe",
            last_name: "Bennett",
            full_address: "90 Queen St, Auckland, New Zealand",
            zip_code: "1010",
            country: "New Zealand",
            city: "Auckland",
            state: "NZ",
            phone: "+64 9 555 1234",
            email: "chloe.bennett@example.nz",
            image: "https://ui-avatars.com/api/?name=Chloe+Bennett&background=0D8ABC&color=fff",
            balance: 1420.8,
            status: false,
            is_admin: false,
        },
        {
            id: 14,
            first_name: "Benjamin",
            last_name: "Ivanov",
            full_address: "3 Red Square, Moscow, Russia",
            zip_code: "101000",
            country: "Russia",
            city: "Moscow",
            state: "MSK",
            phone: "+7 495 123-4567",
            email: "benjamin.ivanov@example.ru",
            image: "https://ui-avatars.com/api/?name=Benjamin+Ivanov&background=0D8ABC&color=fff",
            balance: 1600.65,
            status: true,
            is_admin: true,
        },
        {
            id: 15,
            first_name: "Sofia",
            last_name: "Haddad",
            full_address: "15 Hamra St, Beirut, Lebanon",
            zip_code: "1103",
            country: "Lebanon",
            city: "Beirut",
            state: "BE",
            phone: "+961 1 234 567",
            email: "sofia.haddad@example.lb",
            image: "https://ui-avatars.com/api/?name=Sofia+Haddad&background=0D8ABC&color=fff",
            balance: 1054.8,
            status: true,
            is_admin: false,
        },
        {
            id: 16,
            first_name: "Henry",
            last_name: "Zhou",
            full_address: "81 Nanjing Rd, Shanghai, China",
            zip_code: "200001",
            country: "China",
            city: "Shanghai",
            state: "SH",
            phone: "+86 21 5555 1234",
            email: "henry.zhou@example.cn",
            image: "https://ui-avatars.com/api/?name=Henry+Zhou&background=0D8ABC&color=fff",
            balance: 1842.7,
            status: false,
            is_admin: true,
        },
    ],
};

export default Admin;
