import UserImage from "../assets/images/user.png";
import CoinbaseImage from "../assets/images/coinbase.png";
import CpaImage from "../assets/images/cpa.png";
import CryptoImage from "../assets/images/crypto.png";
import TiktokImage from "../assets/images/tiktok.png";
import RaidImage from "../assets/images/raid.png";
import DominoImage from "../assets/images/domino.png";

const User = {
    first_name: "John",
    last_name: "Doe",
    full_address: "123 Main St, Anytown, USA",
    zip_code: "10116",
    country: "USA",
    city: "New York",
    state: "NY",
    phone: "+1 (123) 456-7890",
    email: "admin@example.com",
    image: UserImage,
    balance: 1561.02,
    is_admin: true,
    Notifications: [
        {
            title: "Welcome!",
            body: "Thank you for signing up.",
            created_at: "3 hours ago",
        },
        {
            title: "Update Available",
            body: "A new update has been released.",
            created_at: "2 hours ago",
        },
    ],
    Apps: [
        {
            id: 1356,
            name: "CoinBase",
            image: CoinbaseImage,
            api_key: "5a0Ds1O45Jas40KJasa0w4a",
            secret_key: "5a0Ds1O45Jas40KJasa0w4a",
            currency: "Coins",
            decimals: 5,
            rate: 75.0,
            postback_receive: "no",
            postback_url: "https://mydomain.com/postback",
            postback_method: "POST",
            date: "Mar 10, 2025",
            status: true,
        },
        {
            id: 6940,
            name: "Offerwall",
            image: CpaImage,
            api_key: "1a5sakjwq4f2a1sd0wr45sf",
            secret_key: "5a0Ds1O45Jas40KJasa0w4a",
            currency: "Points",
            decimals: 2,
            rate: 100.0,
            postback_receive: "yes",
            postback_url: "https://mydomain.com/postback",
            postback_method: "POST",
            date: "Jun 25, 2025",
            status: false,
        },
    ],
    Offers: [
        {
            id: 1,
            name: "Crypto.com",
            image: CryptoImage,
            payout: 52.1,
            revenue: 10.0,
            countries: ["US", "CA", "UK", "FR"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 2,
            name: "TikTok",
            image: TiktokImage,
            payout: 22.01,
            revenue: 5.35,
            countries: ["US", "IT"],
            platforms: ["IOS"],
        },
        {
            id: 3,
            name: "RAID: Shadow Legends",
            image: RaidImage,
            payout: 15.2,
            revenue: 10.3,
            countries: ["EG", "SU"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 4,
            name: "Coinbase",
            image: CoinbaseImage,
            payout: 151.12,
            revenue: 55.1,
            countries: ["UK"],
            platforms: ["Desktop"],
        },
        {
            id: 5,
            name: "Domino Dream",
            image: DominoImage,
            payout: 0.0,
            revenue: 0.0,
            countries: ["CA", "IT", "US"],
            platforms: ["Android", "Desktop"],
        },
        {
            id: 6,
            name: "Adobe Creative Cloud",
            image: "https://picsum.photos/seed/offer-6/300/200",
            payout: 88.83,
            revenue: 36.4,
            countries: ["BR", "US", "IN", "DE"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 7,
            name: "Google One",
            image: "https://picsum.photos/seed/offer-7/300/200",
            payout: 35.89,
            revenue: 17.89,
            countries: ["MX", "US"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 8,
            name: "Trello Gold",
            image: "https://picsum.photos/seed/offer-8/300/200",
            payout: 47.15,
            revenue: 57.86,
            countries: ["IT", "DE", "DK"],
            platforms: ["Desktop", "Android"],
        },
        {
            id: 9,
            name: "Dropbox Plus",
            image: "https://picsum.photos/seed/offer-9/300/200",
            payout: 95.23,
            revenue: 26.09,
            countries: ["FI", "MX"],
            platforms: ["Android"],
        },
        {
            id: 10,
            name: "Apple Music",
            image: "https://picsum.photos/seed/offer-10/300/200",
            payout: 22.34,
            revenue: 6.99,
            countries: ["IT"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 11,
            name: "Vultr",
            image: "https://picsum.photos/seed/offer-11/300/200",
            payout: 28.27,
            revenue: 54.25,
            countries: ["IT", "SE"],
            platforms: ["Desktop"],
        },
        {
            id: 12,
            name: "Disney+",
            image: "https://picsum.photos/seed/offer-12/300/200",
            payout: 36.68,
            revenue: 3.43,
            countries: ["SE", "UK", "MX", "AE"],
            platforms: ["Android"],
        },
        {
            id: 13,
            name: "Skillshare",
            image: "https://picsum.photos/seed/offer-13/300/200",
            payout: 64.99,
            revenue: 23.74,
            countries: ["ES", "SE"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 14,
            name: "Slack Pro",
            image: "https://picsum.photos/seed/offer-14/300/200",
            payout: 35.24,
            revenue: 33.37,
            countries: ["SA", "CN", "IN", "ZA"],
            platforms: ["IOS", "Desktop"],
        },
        {
            id: 15,
            name: "Udemy Course",
            image: "https://picsum.photos/seed/offer-15/300/200",
            payout: 56.13,
            revenue: 6.23,
            countries: ["IT", "DK"],
            platforms: ["Desktop"],
        },
        {
            id: 16,
            name: "DigitalOcean",
            image: "https://picsum.photos/seed/offer-16/300/200",
            payout: 176.21,
            revenue: 51.39,
            countries: ["AE", "DE"],
            platforms: ["Desktop"],
        },
        {
            id: 17,
            name: "Slack Pro",
            image: "https://picsum.photos/seed/offer-17/300/200",
            payout: 182.71,
            revenue: 11.12,
            countries: ["AR", "CA", "CN"],
            platforms: ["Android", "Desktop"],
        },
        {
            id: 18,
            name: "Todoist Premium",
            image: "https://picsum.photos/seed/offer-18/300/200",
            payout: 58.06,
            revenue: 29.17,
            countries: ["NO", "JP"],
            platforms: ["IOS"],
        },
        {
            id: 19,
            name: "TikTok",
            image: "https://picsum.photos/seed/offer-19/300/200",
            payout: 186.27,
            revenue: 14.22,
            countries: ["CA", "RU", "FI", "AR"],
            platforms: ["IOS"],
        },
        {
            id: 20,
            name: "Amazon Gift‑Card Survey",
            image: "https://picsum.photos/seed/offer-20/300/200",
            payout: 24.72,
            revenue: 18.19,
            countries: ["AR", "CN", "BR"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 21,
            name: "Disney+",
            image: "https://picsum.photos/seed/offer-21/300/200",
            payout: 111.83,
            revenue: 57.01,
            countries: ["EG"],
            platforms: ["IOS"],
        },
        {
            id: 22,
            name: "Duolingo Plus",
            image: "https://picsum.photos/seed/offer-22/300/200",
            payout: 108.71,
            revenue: 43.96,
            countries: ["DK"],
            platforms: ["Android"],
        },
        {
            id: 23,
            name: "Grammarly",
            image: "https://picsum.photos/seed/offer-23/300/200",
            payout: 115.95,
            revenue: 17.46,
            countries: ["ES", "ZA", "JP"],
            platforms: ["Desktop"],
        },
        {
            id: 24,
            name: "Zoom Pro",
            image: "https://picsum.photos/seed/offer-24/300/200",
            payout: 53.86,
            revenue: 34.08,
            countries: ["AE"],
            platforms: ["Desktop"],
        },
        {
            id: 25,
            name: "Uber Eats",
            image: "https://picsum.photos/seed/offer-25/300/200",
            payout: 81.79,
            revenue: 14.68,
            countries: ["BR", "US", "ZA", "CN"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 26,
            name: "PayPal Bonus",
            image: "https://picsum.photos/seed/offer-26/300/200",
            payout: 29.79,
            revenue: 19.46,
            countries: ["FR", "IT", "BR"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 27,
            name: "PayPal Bonus",
            image: "https://picsum.photos/seed/offer-27/300/200",
            payout: 182.48,
            revenue: 47.66,
            countries: ["DE", "CN"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 28,
            name: "Coinbase",
            image: "https://picsum.photos/seed/offer-28/300/200",
            payout: 48.2,
            revenue: 21.22,
            countries: ["IT", "ES", "AE"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 29,
            name: "Netflix Trial",
            image: "https://picsum.photos/seed/offer-29/300/200",
            payout: 145.61,
            revenue: 57.48,
            countries: ["ES"],
            platforms: ["IOS", "Desktop"],
        },
        {
            id: 30,
            name: "Adobe Creative Cloud",
            image: "https://picsum.photos/seed/offer-30/300/200",
            payout: 95.61,
            revenue: 8.61,
            countries: ["DE", "IN"],
            platforms: ["IOS"],
        },
        {
            id: 31,
            name: "DigitalOcean",
            image: "https://picsum.photos/seed/offer-31/300/200",
            payout: 70.68,
            revenue: 21.75,
            countries: ["SA", "RU", "CN"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 32,
            name: "Slack Pro",
            image: "https://picsum.photos/seed/offer-32/300/200",
            payout: 43.0,
            revenue: 39.04,
            countries: ["IN", "JP"],
            platforms: ["Desktop"],
        },
        {
            id: 33,
            name: "Vultr",
            image: "https://picsum.photos/seed/offer-33/300/200",
            payout: 110.94,
            revenue: 4.84,
            countries: ["SE", "UK", "NO"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 34,
            name: "Netflix Trial",
            image: "https://picsum.photos/seed/offer-34/300/200",
            payout: 84.0,
            revenue: 58.71,
            countries: ["IT", "ZA", "EG"],
            platforms: ["Android", "Desktop"],
        },
        {
            id: 35,
            name: "Skillshare",
            image: "https://picsum.photos/seed/offer-35/300/200",
            payout: 17.27,
            revenue: 52.39,
            countries: ["IN", "MX", "IT", "AU"],
            platforms: ["Desktop"],
        },
        {
            id: 36,
            name: "GitHub Pro",
            image: "https://picsum.photos/seed/offer-36/300/200",
            payout: 37.06,
            revenue: 12.89,
            countries: ["RU"],
            platforms: ["IOS"],
        },
        {
            id: 37,
            name: "LinkedIn Learning",
            image: "https://picsum.photos/seed/offer-37/300/200",
            payout: 23.71,
            revenue: 54.7,
            countries: ["IN"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 38,
            name: "Notion Pro",
            image: "https://picsum.photos/seed/offer-38/300/200",
            payout: 132.63,
            revenue: 54.39,
            countries: ["NL", "IN", "AR"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 39,
            name: "LinkedIn Learning",
            image: "https://picsum.photos/seed/offer-39/300/200",
            payout: 5.26,
            revenue: 55.49,
            countries: ["DE", "IT", "CA"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 40,
            name: "Zoom Pro",
            image: "https://picsum.photos/seed/offer-40/300/200",
            payout: 80.99,
            revenue: 10.22,
            countries: ["NZ"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 41,
            name: "Skillshare",
            image: "https://picsum.photos/seed/offer-41/300/200",
            payout: 3.08,
            revenue: 51.54,
            countries: ["CA", "SA", "IN"],
            platforms: ["Desktop"],
        },
        {
            id: 42,
            name: "Adobe Creative Cloud",
            image: "https://picsum.photos/seed/offer-42/300/200",
            payout: 169.02,
            revenue: 40.18,
            countries: ["FR", "US", "IN", "NL"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 43,
            name: "Vultr",
            image: "https://picsum.photos/seed/offer-43/300/200",
            payout: 89.69,
            revenue: 5.64,
            countries: ["MX", "IT", "NZ", "US"],
            platforms: ["Android"],
        },
        {
            id: 44,
            name: "Skillshare",
            image: "https://picsum.photos/seed/offer-44/300/200",
            payout: 12.21,
            revenue: 7.11,
            countries: ["JP"],
            platforms: ["IOS"],
        },
        {
            id: 45,
            name: "Microsoft 365",
            image: "https://picsum.photos/seed/offer-45/300/200",
            payout: 111.1,
            revenue: 32.86,
            countries: ["JP", "AU"],
            platforms: ["IOS", "Android", "Desktop"],
        },
        {
            id: 46,
            name: "Disney+",
            image: "https://picsum.photos/seed/offer-46/300/200",
            payout: 57.68,
            revenue: 6.12,
            countries: ["RU"],
            platforms: ["IOS", "Android"],
        },
        {
            id: 47,
            name: "Spotify Premium",
            image: "https://picsum.photos/seed/offer-47/300/200",
            payout: 63.2,
            revenue: 24.36,
            countries: ["IN", "AU"],
            platforms: ["Desktop"],
        },
        {
            id: 48,
            name: "Netflix Trial",
            image: "https://picsum.photos/seed/offer-48/300/200",
            payout: 78.02,
            revenue: 38.31,
            countries: ["NO", "IN", "DK"],
            platforms: ["IOS"],
        },
        {
            id: 49,
            name: "Uber Eats",
            image: "https://picsum.photos/seed/offer-49/300/200",
            payout: 69.89,
            revenue: 51.34,
            countries: ["US", "AR", "IN", "JP"],
            platforms: ["Android", "Desktop"],
        },
        {
            id: 50,
            name: "Linode",
            image: "https://picsum.photos/seed/offer-50/300/200",
            payout: 10.98,
            revenue: 32.91,
            countries: ["RU"],
            platforms: ["IOS", "Android", "Desktop"],
        },
    ],
    Payments: [
        {
            id: 1,
            method_type: "PayPal",
            biling_to: "user@paypal.com",
            date: "Mar 10, 2025",
            revenue: 52.1,
            status: 0,
        },
        {
            id: 2,
            method_type: "Crypto",
            biling_to: "xSa41Ks4Hsa40wkHs0auaIls4KNsjpLs",
            date: "Apr 05, 2025",
            revenue: 136.1,
            status: 1,
        },
        {
            id: 3,
            method_type: "Binance",
            biling_to: "user@paypal.com",
            date: "May 22, 2025",
            revenue: 1252.1,
            status: 2,
        },
    ],
    PaymentInfo: {
        method_type: "PayPal",
        biling_to: "user@paypal.com",
    },
    Reports: [
        {
            id: 1,
            username: "demo",
            offer_name: "TikTok",
            app_name: "AdmApp",
            payout: 2.55,
            revenue: 1.25,
            status: 1,
            postback: 1,
            country: "US",
            date: "Mar 10, 2025",
        },
        {
            id: 2,
            username: "demo",
            offer_name: "SnapEarn",
            app_name: "CashBits",
            payout: 3.1,
            revenue: 1.62,
            status: 1,
            postback: 1,
            country: "CA",
            date: "Apr 02, 2025",
        },
        {
            id: 3,
            username: "demo",
            offer_name: "PlayJoy",
            app_name: "SpinWin",
            payout: 1.75,
            revenue: 0.88,
            status: 0,
            postback: 1,
            country: "GB",
            date: "Feb 15, 2025",
        },
        {
            id: 4,
            username: "demo",
            offer_name: "ShopHero",
            app_name: "DealDash",
            payout: 4.2,
            revenue: 2.02,
            status: 1,
            postback: 1,
            country: "AU",
            date: "Jan 22, 2025",
        },
        {
            id: 5,
            username: "demo",
            offer_name: "FitTrack",
            app_name: "HealthHub",
            payout: 2.95,
            revenue: 1.47,
            status: 1,
            postback: 1,
            country: "DE",
            date: "Mar 28, 2025",
        },
        {
            id: 6,
            username: "demo",
            offer_name: "StreamNow",
            app_name: "VidPlus",
            payout: 3.6,
            revenue: 1.84,
            status: 0,
            postback: 1,
            country: "FR",
            date: "Apr 18, 2025",
        },
        {
            id: 7,
            username: "demo",
            offer_name: "LearnPro",
            app_name: "EduMaster",
            payout: 5.0,
            revenue: 2.55,
            status: 1,
            postback: 1,
            country: "IN",
            date: "May 01, 2025",
        },
        {
            id: 8,
            username: "demo",
            offer_name: "GameLoot",
            app_name: "Questify",
            payout: 1.9,
            revenue: 0.97,
            status: 1,
            postback: 1,
            country: "JP",
            date: "Feb 05, 2025",
        },
        {
            id: 9,
            username: "demo",
            offer_name: "RideEasy",
            app_name: "GoCab",
            payout: 4.75,
            revenue: 2.4,
            status: 0,
            postback: 1,
            country: "BR",
            date: "Jan 30, 2025",
        },
        {
            id: 10,
            username: "demo",
            offer_name: "CookSmart",
            app_name: "MealPrep",
            payout: 2.25,
            revenue: 1.13,
            status: 1,
            postback: 1,
            country: "IT",
            date: "Mar 07, 2025",
        },
        {
            id: 11,
            username: "demo",
            offer_name: "NewsFlash",
            app_name: "DailyBuzz",
            payout: 1.6,
            revenue: 0.8,
            status: 1,
            postback: 1,
            country: "ES",
            date: "Apr 25, 2025",
        },
        {
            id: 12,
            username: "demo",
            offer_name: "PhotoPix",
            app_name: "SnapArt",
            payout: 2.85,
            revenue: 1.45,
            status: 0,
            postback: 1,
            country: "NL",
            date: "Feb 11, 2025",
        },
        {
            id: 13,
            username: "demo",
            offer_name: "TravelGo",
            app_name: "TripWise",
            payout: 6.2,
            revenue: 3.1,
            status: 1,
            postback: 1,
            country: "SG",
            date: "Mar 19, 2025",
        },
        {
            id: 14,
            username: "demo",
            offer_name: "CryptoWin",
            app_name: "CoinQuest",
            payout: 7.5,
            revenue: 3.75,
            status: 1,
            postback: 1,
            country: "KR",
            date: "Apr 09, 2025",
        },
        {
            id: 15,
            username: "demo",
            offer_name: "PuzzleFun",
            app_name: "BrainBox",
            payout: 1.45,
            revenue: 0.72,
            status: 0,
            postback: 1,
            country: "SE",
            date: "Jan 14, 2025",
        },
        {
            id: 16,
            username: "demo",
            offer_name: "BookWorld",
            app_name: "ReadEasy",
            payout: 3.35,
            revenue: 1.69,
            status: 1,
            postback: 1,
            country: "MX",
            date: "Feb 27, 2025",
        },
        {
            id: 17,
            username: "demo",
            offer_name: "MusicMix",
            app_name: "TuneFlow",
            payout: 2.1,
            revenue: 1.05,
            status: 1,
            postback: 1,
            country: "ZA",
            date: "Mar 04, 2025",
        },
        {
            id: 18,
            username: "demo",
            offer_name: "FinancePro",
            app_name: "BudgetBee",
            payout: 5.6,
            revenue: 2.8,
            status: 0,
            postback: 1,
            country: "CH",
            date: "Apr 13, 2025",
        },
        {
            id: 19,
            username: "demo",
            offer_name: "LanguageX",
            app_name: "LingoLeap",
            payout: 4.0,
            revenue: 2.0,
            status: 1,
            postback: 1,
            country: "AR",
            date: "May 05, 2025",
        },
        {
            id: 20,
            username: "demo",
            offer_name: "GardenJoy",
            app_name: "PlantPal",
            payout: 1.8,
            revenue: 0.9,
            status: 1,
            postback: 1,
            country: "NO",
            date: "Jan 18, 2025",
        },
        {
            id: 21,
            username: "demo",
            offer_name: "PetCare",
            app_name: "FurryFriend",
            payout: 2.7,
            revenue: 1.35,
            status: 0,
            postback: 1,
            country: "DK",
            date: "Feb 21, 2025",
        },
        {
            id: 22,
            username: "demo",
            offer_name: "StyleMe",
            app_name: "FitCheck",
            payout: 3.9,
            revenue: 1.95,
            status: 1,
            postback: 1,
            country: "AE",
            date: "Mar 23, 2025",
        },
        {
            id: 23,
            username: "demo",
            offer_name: "MindRelax",
            app_name: "CalmWave",
            payout: 2.4,
            revenue: 1.2,
            status: 1,
            postback: 1,
            country: "NZ",
            date: "Apr 17, 2025",
        },
        {
            id: 24,
            username: "demo",
            offer_name: "HomeFix",
            app_name: "RepairHub",
            payout: 4.85,
            revenue: 2.43,
            status: 0,
            postback: 1,
            country: "TR",
            date: "May 09, 2025",
        },
        {
            id: 25,
            username: "demo",
            offer_name: "AutoScan",
            app_name: "CarCheck",
            payout: 6.05,
            revenue: 3.02,
            status: 1,
            postback: 1,
            country: "PL",
            date: "Jan 26, 2025",
        },
    ],
};

export default User;
